name: hackmotion_test_assignment
description: A Flutter application to inspect golf swing data.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fl_chart: ^0.68.0
  json_annotation: ^4.0.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - data/swings/
